---
- name: Fetch Files from Remote Hosts
  hosts: web
  become: true

  tasks:
    - name: Fetch Single File
      fetch:
        src: /tmp/remote/file.txt
        dest: /tmp/local/file.txt
        flat: yes

    - name: Fetch Multiple Files
      fetch:
        src: "/tmp/remote/{{ item }}"
        dest: "/tmp/local/{{ item }}"
        flat: yes
      with_items:
        - file1.txt
        - file2.txt
        - file3.txt
        - file4.txt

