---
- name: Download Jenkins WAR file
  hosts: web
  gather_facts: false

  tasks:
    - name: Download Jenkins WAR file
      get_url:
        url: https://updates.jenkins.io/latest/jenkins.war
        dest: /opt/jenkins.war

