---
- hosts: localhost
  become: yes
  gather_facts: false
  tasks:
    - name: installing wget 
      apt:
        name: wget
        state: present 
    - name: download Jenkins
      get_url:
        url: https://updates.jenkins-ci.org/download/war/2.248/jenkins.war
        dest: /tmp
    
- hosts: dev
  become: yes
  gather_facts: false
  tasks:
    - name: copy jenkins war to host machines
      copy:
        src: /tmp/jenkins.war
        dest: /opt/jenkins.war
    - name: creating folder structure and running jenkins in the background 
      shell: |
        mkdir -p /opt/jenkins
        mv /opt/jenkins.war /home/opt/jenkins
        nohup java -jar /opt/jenkins/jenkins.war &
