---
- name: Install zip package on CentOS and Ubuntu
  hosts: all
  tasks:
    - name: Install zip package on CentOS
      yum:
        name: git
        state: present
      when: "'CentOS' in ansible_distribution"

    - name: Install zip package on Ubuntu
      apt:
        name: git
        state: present
      when: "'Ubuntu' in ansible_distribution"

