---
- name: Execute Shell Script in a Different Directory
  hosts: web
  gather_facts: false

  tasks:
    - name: Change working directory
      shell:
        cmd: /opt/sample.sh
        chdir: /opt/

